### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by bmicallef1** [bmicallef1/scrum-and-github-flow#1]
**User Story**

As a student I would like to be able to view my grades at any time so I know how I'm doing in my enrolled classes. I should be able to view the total grade for my classes as well as see the grades for every assignment.

* Persona: Student who wants to know there grades.
* Feature: Student is able to view grades for each class they are enrolled in.
* Business Value: Student won't have to ask instructors for grades.

**Acceptance Criteria**
1. Only for the current semester.
2. Works only for chrome.

**Acceptance Test**
1. The student should be able to view the grade they have for each enrolled class
2. The student should be able to view the grades for every assignment in each enrolled class.

**Comment by sjiang1** [comment]
Good! You just need to add proper labels for your issues and resubmit it on Canvas.

**Comment by sjiang1** [comment]
Good job!
